updated to start supporting Chimera

diff --git a/bfinject b/bfinject
--- a/bfinject
+++ b/bfinject
@@ -144,8 +144,15 @@ elif [ -f /jb/usr/local/bin/jtool ]; then
     JTOOL=jtool
     INJECTOR=`pwd`/bfinject4realz
 else
-    echo "[!] Unknown jailbreak. Aborting."
-    exit 1
+    # echo "[!] Unknown jailbreak. Aborting."
+    # exit 1
+    
+    echo "[+] Possible Chimera detected, handling the Electra way ;)"
+    cp jtool.liberios /usr/local/bin/
+    chmod +x /usr/local/bin/jtool.liberios
+    JTOOL=/usr/local/bin/jtool.liberios
+    cp bfinject4realz /usr/local/bin/
+    INJECTOR=/usr/local/bin/bfinject4realz
 fi
 
 
@@ -160,8 +167,8 @@ for DYLIB in ${DYLIBS[@]}; do
     fi
     
     # Use random filenames to avoid cached binaries causing "Killed: 9" messages.
-    RAND=`dd if=/dev/random bs=1 count=16 2>/dev/null | md5`
-    RANDOM_NAME="${INJECTOR%/*}/`dd if=/dev/random bs=1 count=16 2>/dev/null | md5`"
+    RAND=`dd if=/dev/random bs=1 count=16 2>/dev/null | md5sum`
+    RANDOM_NAME="${INJECTOR%/*}/`dd if=/dev/random bs=1 count=16 2>/dev/null | md5sum`"
     DYLIB_DIR="/System/Library/Frameworks/${RAND}.framework"
     DYLIB_PATH="$DYLIB_DIR/$RAND.dylib"
 
